version: '3.9'

services:
  bff:
    build: ./bff
    container_name: bff
    ports:
      - "8080:80"
    networks:
      - rede_app

  api:
    build: ./api
    container_name: api
    ports:
      - "8081:80"
    networks:
      - rede_app

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8082:8080"
    networks:
      - rede_app

  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rede_app

  kong-migration:
    image: kong:3.4
    container_name: kong-migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    command: "kong migrations bootstrap"
    networks:
      - rede_app

  kong:
    image: kong:3.4
    container_name: kong
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"   # Gateway HTTP
      - "8001:8001"   # Admin API
    networks:
      - rede_app

networks:
  rede_app:
    driver: bridge